[tool.poetry]
name = "docs"
version = "0.1.0"
description = "mkdocs - courses"
authors = ["YY Ahn <yongyeol@gmail.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
mkdocs-material = "^8.2.15"
mkdocs-jupyter = "^0.21.0"
mkdocs = "^1.5.2"
